module.exports.translate = {
  locale: "es_ES.UTF-8",
  locale_date_prefix: "El",
  window_default_title: 'Juego de Damas - Juegue en línea gratis',
  meta_description: "Este sitio es dedicado al juego de damas, y es hecho para permitirte encontrar adversarios y jugar en línea con ellos gratuitamente. 2 reglas te son propuestas, la regla del juego internacional y la regla de damas estándar US. Puedes escoger libremente jugar con una o la otra de estas reglas en 2 salas de juego. A tu disposición sobre el sitio, puedes encontrar un historial de tus partidas, y también una clasificación de todos los jugadores.",
  meta_keywords: "juego, juegos, damas, en línea, libre, juego de damas, jueguo de damas gratis, juegue en línea, juego de damas en línea, reglas, peón, rey, jugar a las damas, jugar gratis, jugar en línea, reflexión, estrategia, táctica, torneos, competencia, juegos gratis, juegos en línea, jugar juegos, checkers, online, free",
  fb_app_id: '485355868179398',
  fb_zone: 'es_ES',
  analytics_ua: 'UA-350084-28',
	adsense_slot1: "5228526767",
	adsense_slot2: "3434051562",
	adsense_slot3: "1678116763",
  adsense_slot4: "4671622364",
  header_partners_list: [
    {href: "http://www.ofree.net/", target:"_blank", title:"Only free samples, free stuff, freebies, free laptops, free gift cards, free beauty stuff", src:"img/partners/ofree.gif", height:"31", width:"88", border:"0", alt:""}
  ],
  menu_home_anchor: 'inicio',
  menu_home_title: 'Inicio',
  menu_game_rooms_anchor: 'salas-de-juego',
  menu_game_rooms_title: 'Salas de juego',
  anchors_map: {
		'inicio': 'home', 
		'salas-de-juego': 'game-rooms',
    'registrarse': 'registration',
 		'tu-cuenta': 'registration',
    'iniciar-sesion': 'sign-in',
		'identificadores-perdidos': 'lost-identifiers',
    'update-account-ok': 'update-account-ok'
  },
  mobile_version_display: 'versión móvil',
  page_ranking_title: "Clasificación de los jugadores",
  page_ranking_title_mob: "Clasificación",
  menu_rules_anchor: 'reglas',
  menu_rules_title: 'Reglas',
  menu_help_anchor: 'ayuda',
  menu_help_title: 'Ayuda',
  menu_on_facebook_title: 'En Facebook',
  fb_page_url: 'https://www.facebook.com/pages/Juegodedamas/210923665719645',
	menu_fb_use_account_title: 'Conectarse con su cuenta de Facebook',
	menu_fb_use_account_anchor: 'fb_connect',
	menu_register_title: 'Registrarse',
	menu_register_anchor: 'registrarse',
	menu_sign_in_title: 'Iniciar sesión',
	menu_sign_in_anchor: 'iniciar-sesion',
	menu_update_title: 'Tu cuenta',
	menu_update_anchor: 'tu-cuenta',
	menu_sign_out_title: 'Finalizar sesión',
	menu_sign_out_anchor: 'finalizar-sesion',
	menu_user_welcome: 'Bienvenida',
	menu_user_logged_in: "Apareces como",
	paypal_donation_button_id: '8PCDVPMFW5GUE',
	paypal_donation_button_image: 'https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donate_LG.gif',
	paypal_donation_button_alt: 'PayPal. La forma rápida y segura de pagar en Internet.',
	paypal_to_contribute: 'para apoyar a esta página web',
  footer_partners_list: [
    {href: "http://www.jigsaw-puzzles.net/", target:"_blank", title:"Jigsaw puzzles online for free", text:"Jigsaw puzzles"}
  ],
  page_home_welcome: [
    "Bienvenidos al sitio Juego-de-Damas !",
    "Este sitio es dedicado al juego de damas, y es hecho para permitirte encontrar adversarios y jugar en línea con ellos gratuitamente.",
    "2 reglas te son propuestas, la regla del <a href=\"javascript: void(0)\" onclick=\"return page.load_rules(1); return false;\">juego internacional</a> y la regla de <a href=\"javascript: void(0)\" onclick=\"return page.load_rules(2); return false;\">damas estándar US</a>. Puedes escoger libremente jugar con una o la otra de estas reglas en 2 <a href=\"#salas-de-juego\">salas de juego</a>.",
    "Para poder entrar en una sala de juego, debes ser registrado. Registrándote, escoges un pseudo que le identificará y quedará único más tarde. Para eso, ve a la página <a href=\"#registrarse\">registrarse</a>.",
    "Puntos son atribuidos para cada partida jugada : una bonificación de 2 puntos (+2) para el vencedor y un recargo de 1 punto (-1) para el perdedor. Las tablas también pueden ser pedidas, y si son aceptadas una bonificación de 1 punto (+1) es atribuida a cada adversario.",
    "Atención, si dejas una partida corriente entonces estás considerado como perdedor y su adversario como vencedor, y los puntos son atribuidos del mismo modo.",
    "A tu disposición sobre el sitio, puedes encontrar un <a href=\"javascript: void(0)\" onclick=\"return page.load_history(); return false;\">historial</a> de tus partidas, y también una <a href=\"javascript: void(0)\" onclick=\"return page.load_ranking(); return false;\">clasificación</a> de todos los jugadores.",
    "Sigue las noticias que se exhiben más bajo en esta página y no vaciles en consultar la página <a href=\"javascript: void(0)\" onclick=\"return page.load_help(); return false;\">ayuda</a>."
  ],
	page_home_news: 'Noticias',
  page_history_title: 'Sus partidas',
	page_sign_in_title: 'Iniciar sesión',
	page_sign_in_intro: 'Indica tu nombre de usuario y tu contraseña más abajo',
	page_sign_in_username: 'Usuario',
	page_sign_in_password: 'Contraseña',
	page_sign_in_remember_me: 'Recuérdeme',
	page_sign_in_register_notice: '¿No registrado aún?', 
	page_sign_in_validate: 'Conectarse',
	page_sign_in_token_error: 'Había un problema inesperado',
	page_sign_in_username_error: 'Indica su nombre de usuario',
	page_sign_in_password_error: 'Indica su contraseña',  
	page_sign_in_invalid_error: 'Nombre de usuario o contraseña inválida',
  page_sign_in_inactive_account_error: 'Tu registro no ha sido completado',
	page_lost_ids_anchor: 'identificadores-perdidos',
	page_lost_ids_title: 'Identificadores perdidos',
	page_lost_ids_intro: 'Indica el correo electrónico que utilizaste para tu registro, recibirás entonces un mensaje para recordar tu identificadores.',
	page_lost_ids_email: 'Correo electrónico',
  page_lost_ids_token_error: 'Había un problema inesperado',
	page_lost_ids_email_error: 'Dirección de correo electrónico inválido',
  page_lost_ids_email_unknown_error: 'Dirección de correo imposible de encontrar',
  page_lost_ids_inactive_account_error: 'Tu registro no ha sido completado',
	page_lost_ids_validate: 'Validar',
  page_lost_ids_ok_title: '¡Es OK!',
  page_lost_ids_ok_message: 'Un correo electrónico te ha sido enviado con tu identificadores.',
  mail_confirm_subject: "[Juego-de-Damas.net] Enlace de confirmación",
  mail_confirm_body: [
    "Buenos días,",
    "Recibes este correo electrónico porque pediste ser inscrito en el sitio Juego-de-Damas.net.",
    "Por favor, encuentra más abajo el enlace de confirmación para completar tu registro :",
    "%%LINK%%",
    "Haz clic en el enlace o bien, tan necesario, copialo y pegalo en la barra de dirección de tu navegador.",
    "Si no estás al principio de esta solicitud, por favor excusa el disgusto ocasionado.",
    "No es necesario responder a este correo, ha sido enviado por un robot.",
    "El equipo de Juego-de-damas.net."
  ],
  mail_lost_ids_subject: '[Juego-de-Damas.net] Tu identificadores',
  mail_lost_ids_body: [
    "Buenos días,",
    "Recibes este correo electrónico porque pediste un recuerdo de tu identificadores en el sitio Juego-de-Damas.net.",
    "Por favor, encuentre estos identificadores más abajo :",
    "Usuario : <b>%%LOGIN%%</b>",
    "Contraseña : <b>%%PASSWORD%%</b>",
    "Si no estás al principio de esta solicitud, por favor excusa el disgusto ocasionado.",
    "No es necesario responder a este correo, ha sido enviado por un robot.",
    "Estaremos contentos de verte de nuevo pronto !",
    "El equipo de Juego-de-damas.net."
  ],
  page_register_title: 'Registrarse',
	page_register_intro: 'Rellena el formulario más abajo para registrarte. Esto es necesario para acceder a las salas de juego. Todos los campos son obligatorios, y sé asegurado que tus informaciones personales como tu nombre y tu correo electrónico quedarán confidenciales. Pero puedes también conectarte con tu cuenta Facebook (ver el botón más arriba)',
	page_register_first_name: 'Apellido',
	page_register_last_name: 'Nombre',
	page_register_gender: 'Género',
	page_register_gender_m: 'Hombre',
	page_register_gender_f: 'Mujer',
	page_register_country: 'País',
	page_register_email: 'Correo electrónico',
	page_register_username: 'Usuario',
	page_register_password: 'Contraseña',
	page_register_confirmation: 'Confirmación',
	page_register_appearance: 'Apariencia',
	page_register_optin_notice: 'Acepto recibir mensajes de información de esta página web',
	page_register_username_notice: 'Te presentarás con este nombre de usuario en las salas de juego, y nadie será autorizado a utilizarlo cuando serás registrado',
	page_register_appearance_notice: 'Escoge una cara, si no aparecerás con la cara por defecto (Alien)',
	page_register_email_notice: 'Atención: la dirección de correo electrónico debe ser válida, un enlace de confirmación te será enviado a esta dirección',
	page_register_password_notice: 'Solamente si deseas cambiarlo',
	page_register_password_format: '(6 a 24 caracteres)',
	page_register_first_name_error: 'Indica tu apellido',
	page_register_last_name_error: 'Indica tu nombre',
	page_register_gender_error: 'Indica tu género',
	page_register_country_error: 'Indica tu país',
	page_register_email_error: 'Indica una dirección de correo electrónico válida',
	page_register_username_error: 'Escoge un nombre de usuario',
	page_register_password_error: 'La contraseña no es válida',
	page_register_confirmation_error: 'Error en la confirmación de la contraseña',
	page_register_global_error: 'El formulario contiene errores, encontrarás las instrucciones en rojo, más arriba',
	page_register_get_email_notice: [
	  'Gracias por tu registro. Un correo electrónico ha sido enviado a la dirección %%EMAIL%% con un enlace de confirmación. Sigue este enlace para completar tu registro.',
    '¡Si no recibiste este correo electrónico de algunos minutos, verifica entonces en la carpeta <b>Indeseables</b> o <b>Spams</> de tu mensajería, forzosamente se encuentra allí!',
    '¡Hasta pronto en el sitio!'
  ],
	page_register_completed_notice: [
    '¡Aúpa! Tu registro ahora es completo. Puedes entrar el nombre de usuario y la contraseña que has escogido para acceder a las salas de juego',
		'¡Diviértate bien!'
  ],
	page_register_token_error: 'Había un problema inesperado (probablemente tu sesión fue perdida). Por favor intenta otra vez',
	page_register_unexpected_error: 'Problema inesperado. Por favor intenta otra vez',
	page_register_login_exists_error: 'Este nombre de usuario ya existe',
	page_register_email_exists_error: 'Una cuenta ya ha sido registrada con este correo electrónico',
	page_register_validate: 'Registrar',
	page_update_title: 'Tu cuenta',
	page_update_intro: 'Encuentra más abajo todas las informaciones relativas a tu cuenta para efectuar cambios. Sé asegurado que tus informaciones personales como tu nombre y tu correo electrónico quedarán confidenciales.',
	page_update_validate: 'Actualizar',
	page_update_ok_title: '¡Es OK!',
  page_update_ok_message: 'Las modificaciones han sido registradas.',
	page_fb_sign_in_title: 'Conexión Facebook',
	page_fb_sign_in_intro: 'Así como es la primera vez que te conectas con tu cuenta Facebook, completa tu registro con algunas informaciones más abajo, esto es necesario para acceder a las salas de juego.',
	page_fb_update_title: 'Tu cuenta',
	page_fb_update_intro: 'Encuentra más abajo todas las informaciones relativas a tu cuenta para efectuar cambios.',
  page_game_rooms_title: 'Salas de juego',
	page_game_rooms_rooms_intro: 'Debajo está la lista de las salas de juego disponibles. Haz clic en una sala para entrar.',
	page_game_rooms_room: 'Sala',
	page_game_rooms_rules: 'Reglas',
	page_game_rooms_user_in_room: 'jugador en la sala',
	page_game_rooms_users_in_room: 'jugadores en la sala',
	page_game_rooms_game_in_course: 'partida corriente',
	page_game_rooms_games_in_course: 'partidas corrientes',
	page_game_rooms_in_room_intro: 'Debajo está la lista de los jugadores disponibles y las partidas corrientes. Haz clic en un jugador para invitarle a una partida.',
	page_game_rooms_in_room_back: 'Vuelta a la lista de las salas',
	page_game_rooms_in_room_quit: 'Dejar la sala',
	page_game_rooms_available_players: 'jugadores disponibles',
};