module.exports.translate = {
  locale: "fr_FR.UTF-8",
  locale_date_prefix: "Le",
  window_default_title: 'Jeu de Dames - Jouez en ligne gratuitement',
  meta_description: "Ce site est dédié au jeu de dames, et il est fait pour vous permettre de trouver des adversaires et jouer en ligne avec eux gratuitement. 2 règles vous sont proposées, celle du jeu international et celle des checkers standard US, et vous pouvez choisir librement de jouer avec l'une ou l'autre de ces règles dans 2 salons de jeu. Vous pouvez trouver à votre disposition sur le site un historique de vos parties, ainsi qu'un classement de tous les joueurs.",
  meta_keywords: "jeu, jeux, dames, en ligne, gratuit, jeu de dames, jeu de dame, jeux de dames, jeu de dames gratuit, jeu dames, jeux dames, jeu dames gratuit, jeux dames gratuit, jeux dames gratuits, jeu dames en ligne, jeux dames en ligne, règles, pion, dame, jouer aux dames, jouer gratuitement, jouer en ligne, réflexion, strategie, tactique, tournois, compétition, jeux gratuit, jeux en ligne, jouer aux jeux, jeux gratuits, checkers, online, free",
  fb_app_id: '121623414679389',
  fb_zone: 'fr_FR',
  analytics_ua: 'UA-350084-21',
	adsense_slot1: "3531467566",
	adsense_slot2: "6527118768",
	adsense_slot3: "9061782769",
  adsense_slot4: "6287956364",
  header_partners_list: [
    {href: "http://www.mesjeuxvirtuels.com", target:"_blank", title:"Mes jeux Virtuels - Annuaire des jeux gratuits en ligne", src:"img/partners/mesjeuxvirtuels.gif", height:"31", width:"88", border:"0", alt:""}
  ],
  menu_home_anchor: 'accueil',
  menu_home_title: 'Accueil',
  menu_game_rooms_anchor: 'salons-de-jeu',
  menu_game_rooms_title: 'Salons de jeu',
  anchors_map: {
		'accueil': 'home', 
		'salons-de-jeu': 'game-rooms',
    'enregistrement': 'registration',
 		'votre-compte': 'registration',
    'connexion': 'sign-in',
		'identifiants-perdus': 'lost-identifiers',
    'update-account-ok': 'update-account-ok'
  },
  mobile_version_display: 'version mobile',
  page_ranking_title: "Classement des joueurs",
  page_ranking_title_mob: "Classement",
  menu_rules_anchor: 'regles',
  menu_rules_title: 'Règles',
  menu_help_anchor: 'aide',
  menu_help_title: 'Aide',
  menu_on_facebook_title: 'Sur Facebook',
  fb_page_url: 'https://www.facebook.com/pages/Jeudedames/424712074271420',
	menu_fb_use_account_title: 'Se connecter avec son compte Facebook',
	menu_fb_use_account_anchor: 'fb_connect',
	menu_register_title: 'Enregistrement',
	menu_register_anchor: 'enregistrement',
	menu_sign_in_title: 'Connexion',
	menu_sign_in_anchor: 'connexion',
	menu_update_title: 'Votre compte',
	menu_update_anchor: 'votre-compte',
	menu_sign_out_title: 'Déconnexion',
	menu_sign_out_anchor: 'deconnexion',
	menu_user_welcome: 'Bienvenue',
	menu_user_logged_in: 'Vous apparaissez comme',
	paypal_donation_button_id: 'P4HQ9XP8NTRCU',
	paypal_donation_button_image: 'https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donate_LG.gif',
	paypal_donation_button_alt: 'PayPal - la solution de paiement en ligne la plus simple et la plus sécurisée !',
	paypal_to_contribute: 'pour soutenir ce site',
  footer_partners_list: [
    {href: "http://www.jeu-de-puzzle.net/", target:"_blank", title:"Jeu de puzzle gratuit en ligne", text:"Jeu de puzzle"}
  ],
  page_home_welcome: [
		"Bienvenue sur le site Jeu-de-Dames !",
    "Ce site est dédié au jeu de dames, et il est fait pour vous permettre de trouver des adversaires et jouer en ligne avec eux gratuitement.",
    "2 règles vous sont proposées, celle du <a href=\"javascript: void(0)\" onclick=\"return page.load_rules(1); return false;\">jeu international</a> et celle des <a href=\"javascript: void(0)\" onclick=\"return page.load_rules(2); return false;\">checkers standard US</a>, et vous pouvez choisir librement de jouer avec l'une ou l'autre de ces règles dans 2 <a href=\"#salons-de-jeu\">salons de jeu</a>.",
    "Pour pouvoir entrer dans un salon de jeu, vous devez être enregistré. En vous enregistrant, vous choisissez un pseudo qui vous identifiera et restera unique par la suite. Pour cela, rendez-vous sur la page <a href=\"#enregistrement\">enregistrement</a>.",
    "Des points sont attribués pour chaque partie jouée : un bonus de 2 points (+2) pour le vainqueur et un malus de 1 point (-1) pour le perdant. La partie nulle peut également être demandée, et si elle est acceptée un bonus de 1 point (+1) est alors attribué à chaque adversaire.",
    "Attention, si vous quittez une partie en cours vous êtes alors considéré comme perdant et votre adversaire comme vainqueur, et les points sont attribués de la même façon.",
    "Vous pouvez trouver à votre disposition sur le site un <a href=\"javascript: void(0)\" onclick=\"return page.load_history(); return false;\">historique</a> de vos parties, ainsi qu'un <a href=\"javascript: void(0)\" onclick=\"return page.load_ranking(); return false;\">classement</a> de tous les joueurs.",
    "Suivez les nouveautés qui s'affichent plus bas sur cette page et n'hésitez pas à consulter la page <a href=\"javascript: void(0)\" onclick=\"return page.load_help(); return false;\">aide</a>."
  ],
	page_home_news: 'Nouveautés',
  page_history_title: 'Vos parties',
	page_sign_in_title: 'Connexion',
	page_sign_in_intro: 'Indiquez votre pseudo et votre mot de passe ci-dessous',
	page_sign_in_username: 'Pseudo',
	page_sign_in_password: 'Mot de passe',
	page_sign_in_remember_me: 'Se souvenir de moi',
	page_sign_in_register_notice: 'Pas encore enregistré ? ', 
	page_sign_in_validate: 'Se connecter',
	page_sign_in_token_error: 'Un problème inattendu est survenu',
	page_sign_in_username_error: 'Indiquez votre pseudo',
	page_sign_in_password_error: 'Indiquez votre mot de passe',  
	page_sign_in_invalid_error: 'Pseudo ou mot de passe invalide',
  page_sign_in_inactive_account_error: 'Votre enregistrement n\'a pas été complété',
	page_lost_ids_anchor: 'identifiants-perdus',
	page_lost_ids_title: 'Identifiants perdus',
	page_lost_ids_intro: 'Indiquez l\'adresse e-mail que vous avez utilisée pour votre enregistrement, vous recevrez alors un message pour vous rappeler vos identifiants.',
	page_lost_ids_email: 'E-mail',
  page_lost_ids_token_error: 'Un problème inattendu est survenu',
	page_lost_ids_email_error: 'E-mail invalide',
  page_lost_ids_email_unknown_error: 'E-mail introuvable',
  page_lost_ids_inactive_account_error: 'Votre enregistrement n\'a pas été complété',
	page_lost_ids_validate: 'Envoyer',
  page_lost_ids_ok_title: 'C\'est Ok !',
  page_lost_ids_ok_message: 'Un e-mail vous a été envoyé avec vos identifiants.',
  mail_confirm_subject: "[Jeu-de-Dames.net] Lien de confirmation",
  mail_confirm_body: [
    "Bonjour,",
    "Vous recevez ce message car vous avez demandé à être inscrit sur le site Jeu-de-Dames.net.",
    "Veuillez trouver ci-dessous le lien de confirmation utile pour compléter votre enregistrement :",
    "%%LINK%%",
    "Cliquez juste sur le lien ou bien, si nécessaire, copiez-le et collez-le dans la barre d'adresse de votre navigateur.",
    "Si vous n'êtes pas à l'origine de cette demande, veuillez excuser le désagrément occasionné.",
    "Il n'est pas nécessaire de répondre à ce message, il a été envoyé par un robot.",
    "L'équipe de Jeu-de-Dames.net."
  ],
  mail_lost_ids_subject: '[Jeu-de-Dames.net] Vos identifiants',
  mail_lost_ids_body: [
    "Bonjour,",
    "Vous recevez ce message car vous avez demandé un rappel de vos identifiants sur le site Jeu-de-Dames.net.",
    "Veuillez trouver ces identifiants ci-dessous :",
    "Pseudo : <b>%%LOGIN%%</b>",
    "Mot de passe : <b>%%PASSWORD%%</b>",
    "Si vous n'êtes pas à l'origine de cette demande, veuillez excuser le désagrément occasionné.",
    "Il n'est pas nécessaire de répondre à ce message, il a été envoyé par un robot.",
    "Nous serons contents de vous revoir bientôt !",
    "L'équipe de Jeu-de-Dames.net."
  ],
  page_register_title: 'Enregistrement',
	page_register_intro: 'Complétez le formulaire ci-dessous pour vous enregistrer. Cela est nécessaire pour accéder aux salons de jeu. Tous les champs sont obligatoires, et soyez assuré que vos informations personnelles comme votre nom et votre e-mail resteront confidentielles. Notez que vous pouvez à la place vous connecter avec votre compte Facebook (voir le bouton ci-dessus)',
	page_register_first_name: 'Prénom',
	page_register_last_name: 'Nom',
	page_register_gender: 'Genre',
	page_register_gender_m: 'Homme',
	page_register_gender_f: 'Femme',
	page_register_country: 'Pays',
	page_register_email: 'E-mail',
	page_register_username: 'Pseudo',
	page_register_password: 'Mot de passe',
	page_register_confirmation: 'Confirmation',
	page_register_appearance: 'Apparence',
	page_register_optin_notice: 'J\'accepte de recevoir des messages d\'information de la part de ce site',
	page_register_username_notice: 'Vous vous présenterez avec ce pseudo dans les salons de jeu, et personne ne sera autorisé à l\'utiliser une fois que vous serez enregistré',
	page_register_appearance_notice: 'Choisissez un visage, sinon vous apparaîtrez avec celui par défaut (Alien)',
	page_register_email_notice: 'Attention : l\'adresse e-mail doit être valable, un lien de confirmation vous sera envoyé à cette adresse',
	page_register_password_notice: 'Seulement si vous souhaitez le changer',
	page_register_password_format: '(6 à 24 caractères)',
	page_register_first_name_error: 'Indiquez votre prénom',
	page_register_last_name_error: 'Indiquez votre nom',
	page_register_gender_error: 'Indiquez votre genre',
	page_register_country_error: 'Indiquez votre pays',
	page_register_email_error: 'Indiquez une adresse e-mail valide',
	page_register_username_error: 'Choisissez un pseudo',
	page_register_password_error: 'Le mot de passe n\\\'est pas valide',
	page_register_confirmation_error: 'Erreur dans la confirmation du mot de passe',
	page_register_global_error: 'Le formulaire comporte des erreurs, vous trouverez les instructions en rouge ci-dessus',
	page_register_get_email_notice: [
	  'Merci pour votre enregistrement. Un e-mail a été envoyé à l\'adresse <a href="mailto:%%EMAIL%%">%%EMAIL%%</a> avec un lien de confirmation. Suivez ce lien pour compléter votre enregistrement.',
    'Si vous n\'avez pas reçu cet e-mail d\'ici quelques minutes, vérifiez alors dans le dossier <b>Indésirables</b> ou <b>Spams</b> de votre messagerie, il s\'y trouve forcément !',
    'À très bientôt sur le site !'
  ],
	page_register_completed_notice: [
    'Super ! Votre enregistrement est maintenant complet. Affichez la page <a href="javascript: void(0)" onclick="return user.sign_in(); return false;">Connexion</a> et entrez votre pseudo et votre mot de passe pour accéder aux salons de jeu.',
		'Amusez-vous bien !'
  ],
	page_register_token_error: 'Un problème inattendu est survenu (vous avez probablement perdu votre session). Essayez à nouveau',
	page_register_unexpected_error: 'Problème inattendu. Essayez à nouveau',
	page_register_login_exists_error: 'Ce pseudo existe déjà',
	page_register_email_exists_error: 'Un compte a déjà été enregistré avec cette adresse e-mail',
	page_register_validate: 'Enregistrer',
	page_update_title: 'Votre compte',
	page_update_intro: 'Retrouvez ci-dessous toutes les informations relatives à votre compte pour effectuer des changements. Soyez assuré que vos informations personnelles comme votre nom et votre e-mail resteront confidentielles.',
	page_update_validate: 'Mettre à jour',
	page_update_ok_title: 'C\'est Ok !',
  page_update_ok_message: 'Les modifications ont bien été enregistrées.',
	page_fb_sign_in_title: 'Connexion Facebook',
	page_fb_sign_in_intro: 'Comme c\'est la première fois que vous vous connectez avec votre compte Facebook, complétez votre enregistrement avec les quelques informations ci-dessous, cela est nécessaire pour accéder aux salons de jeu.',
	page_fb_update_title: 'Votre compte',
	page_fb_update_intro: 'Retrouvez ci-dessous toutes les informations relatives à votre compte pour effectuer des changements.',
  page_game_rooms_title: 'Salons de jeu',
	page_game_rooms_rooms_intro: 'Vous pouvez trouver ci-dessous la liste des salons de jeu disponibles. Cliquez sur un salon pour y entrer.',
	page_game_rooms_room: 'Salon',
	page_game_rooms_rules: 'Règles',
	page_game_rooms_user_in_room: 'joueur dans le salon',
	page_game_rooms_users_in_room: 'joueurs dans le salon',
	page_game_rooms_game_in_course: 'partie en cours',
	page_game_rooms_games_in_course: 'parties en cours',
	page_game_rooms_in_room_intro: 'Vous pouvez trouver ci-dessous la liste des joueurs disponibles et les parties en cours. Cliquez sur un joueur pour l\'inviter à une partie.',
	page_game_rooms_in_room_back: 'Retour à la liste des salons',
	page_game_rooms_in_room_quit: 'Quitter le salon',
	page_game_rooms_available_players: 'joueurs disponibles',
};