module.exports.translate = {
  locale: "en_US.UTF-8",
  locale_date_prefix: "On",
  window_default_title: 'Checkers Game - Play online for free',
  meta_description: "This site, dedicated to the checkers, is made to allow you to find opponents and to play online with them for free. 2 rules are proposed, the international game one and the standard US checkers one. You can freely choose one rule or the other and play in 2 game rooms. You can find at your disposal, on the site, an history of your games, and the ranking of all the players.",
  meta_keywords: "game, games, checkers, online, free, checkers game, play free chechers, checker game, free checkers game, checkers game online, rules, pawn, king, play checkers, play for free, play online, reflection, strategy, tactics, tournaments, competition, free games, online games, play games, free games",
  fb_app_id: '331202373657443',
  fb_zone: 'en_US',
  analytics_ua: 'UA-350084-27',
	adsense_slot1: "5077409566",
	adsense_slot2: "9480585167",
	adsense_slot3: "6108316361",
  adsense_slot4: "1718155962",
  header_partners_list: [
    {href: "http://www.ofree.net/", target:"_blank", title:"Only free samples, free stuff, freebies, free laptops, free gift cards, free beauty stuff", src:"img/partners/ofree.gif", height:"31", width:"88", border:"0", alt:""}
  ],
  menu_home_anchor: 'home',
  menu_home_title: 'Home',
  menu_game_rooms_anchor: 'game-rooms',
  menu_game_rooms_title: 'Game rooms',
  anchors_map: {
		'home': 'home', 
		'game-rooms': 'game-rooms',
    'registration': 'registration',
 		'your-account': 'registration',
    'sign-in': 'sign-in',
		'lost-identifiers': 'lost-identifiers',
    'update-account-ok': 'update-account-ok'
  },
  mobile_version_display: 'mobile version',
  page_ranking_title: "Players ranking",
  page_ranking_title_mob: "Ranking",
  menu_rules_anchor: 'rules',
  menu_rules_title: 'Rules',
  menu_help_anchor: 'help',
  menu_help_title: 'Help',
  menu_on_facebook_title: 'On Facebook',
  fb_page_url: 'https://www.facebook.com/CheckersGame',
	menu_fb_use_account_title: 'Sign in with your Facebook account',
	menu_fb_use_account_anchor: 'fb_connect',
	menu_register_title: 'Registration',
	menu_register_anchor: 'registration',
	menu_sign_in_title: 'Sign in',
	menu_sign_in_anchor: 'sign-in',
	menu_update_title: 'Your account',
	menu_update_anchor: 'your-account',
	menu_sign_out_title: 'Sign out',
	menu_sign_out_anchor: 'sign-out',
	menu_user_welcome: 'Welcome',
	menu_user_logged_in: 'You\'re seen as',
	paypal_donation_button_id: '3ZJPKZ3972744',
	paypal_donation_button_image: 'https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif',
	paypal_donation_button_alt: 'PayPal - The safer, easier way to pay online!',
	paypal_to_contribute: 'to support this site',
  footer_partners_list: [
    {href: "http://www.jigsaw-puzzles.net/", target:"_blank", title:"Jigsaw puzzles online for free", text:"Jigsaw puzzles"}
  ],
  page_home_welcome: [
    "Welcome to the site Checkers-Game !",
	  "This site, dedicated to the checkers, is made to allow you to find opponents and to play online with them for free.",
    "2 rules are proposed, the <a href=\"javascript: void(0)\" onclick=\"return page.load_rules(1); return false;\">international game</a> one and the <a href=\"javascript: void(0)\" onclick=\"return page.load_rules(2); return false;\">standard US checkers</a> one. You can freely choose one rule or the other and play in 2 <a href=\"#game-rooms\">game rooms</a>.",
    "To enter into a game room, you have to be registered. When registering, you choose a pseudo which will identify you and will remain only yours afterwards. For this purpose, go on the page <a href=\"#registration\">registration</a>.",
    "Points are awarded for every played game : a bonus of 2 points (+2) for the winner and a penalty of 1 point (-1) for the loser. The draw can be asked, and if it is accepted a bonus of 1 point (+1) is awarded to every opponent.",
	  "Warning : if you leave a current game you are considered as the loser, your opponent is the winner and the points are awarded in the same way.",
    "You can find at your disposal, on the site, an <a href=\"javascript: void(0)\" onclick=\"return page.load_history(); return false;\">history</a> of your games, and the <a href=\"javascript: void(0)\" onclick=\"return page.load_ranking(); return false;\">ranking</a> of all the players.",
    "Follow the news displayed lower on this page and feel free to consult the <a href=\"javascript: void(0)\" onclick=\"return page.load_help(); return false;\">help</a> page."
  ],
	page_home_news: 'News',
  page_history_title: 'Your games',
  page_sign_in_title: 'Sign in',
	page_sign_in_intro: 'Please indicate your username and password below',
	page_sign_in_username: 'Username',
	page_sign_in_password: 'Password',
	page_sign_in_remember_me: 'Remember me',
	page_sign_in_register_notice: 'Not registered yet ? Go to', 
	page_sign_in_validate: 'Sign in',
	page_sign_in_token_error: 'Unexpected problem',
	page_sign_in_username_error: 'Indicate your username',
	page_sign_in_password_error: 'Indicate your password',  
	page_sign_in_invalid_error: 'Invalid username or password',
  page_sign_in_inactive_account_error: 'Your registration is not completed',
	page_lost_ids_anchor: 'lost-identifiers',
  page_lost_ids_title: 'Lost identifiers',
	page_lost_ids_intro: 'Please indicate the email you\'ve used for your registration, then you will receive a message to remember your identifiers.',
	page_lost_ids_email: 'Email',
  page_lost_ids_token_error: 'Unexpected problem',
  page_lost_ids_email_error: 'Invalid email address',
  page_lost_ids_email_unknown_error: 'Email not found',
  page_lost_ids_inactive_account_error: 'Your registration is not completed',
	page_lost_ids_validate: 'Validate',
  page_lost_ids_ok_title: 'It\'s Ok !',
  page_lost_ids_ok_message: 'An email has been sent to you with your identifiers.',
  mail_confirm_subject: "[Checkers-Game.net] Confirmation link",
  mail_confirm_body: [
    "Hello,",
    "You're receiving this message because you asked to be registered on the site Checkers-Game.net.",
    "Please find below the confirmation link to complete your registration :",
    "%%LINK%%",
    "Just click on it or, if necessary, copy it and paste it into your browser address bar.",
    "If you're not at the origin of this request, please excuse the caused inconvenient.",
    "It's not necessary to reply to this message, it has been sent by a robot.",
    "The Checkers-Game.net team."
  ],
  mail_lost_ids_subject: '[Checkers-Game.net] Your identifiers',
  mail_lost_ids_body: [
    "Hello,",
    "You're receiving this message because you asked to be remembered of your identifiers on the site Checkers-Game.net.",
    "Please find those identifiers below :",
    "Username : <b>%%LOGIN%%</b>",
    "Password : <b>%%PASSWORD%%</b>",
    "If you're not at the origin of this request, please excuse the caused inconvenient.",
    "It's not necessary to reply to this message, it has been sent by a robot.",
    "We'll be glad to see you again soon !",
    "The Checkers-Game.net team."
  ],
  page_register_title: 'Registration',
	page_register_intro: 'Please fill in the form below to register. It is necessary to access to the game rooms. All fields are mandatory, and be sure your personal information such as your name and your email will be kept private. Note that alternately you can sign in with your Facebook account (see the button above)',
	page_register_first_name: 'First Name',
	page_register_last_name: 'Last Name',
	page_register_gender: 'Gender',
	page_register_gender_m: 'Male',
	page_register_gender_f: 'Female',
	page_register_country: 'Country',
	page_register_email: 'Email',
	page_register_username: 'Username',
	page_register_password: 'Password',
	page_register_confirmation: 'Confirmation',
	page_register_appearance: 'Appearance',
	page_register_optin_notice: 'I accept to receive information messages from this website',
	page_register_username_notice: 'You will appear with this name into the game rooms and no one else will be allowed to use it after you have registered',
	page_register_appearance_notice: 'Please choose a face, otherwise you will appear with the default one (Alien)',
	page_register_email_notice: 'Caution : the email address must be valid, a confirmation link will be sent to this address',
	page_register_password_notice: 'Only if you want to change it',
	page_register_password_format: '(6 to 24 characters)',
	page_register_first_name_error: 'Indicate your first name',
	page_register_last_name_error: 'Indicate your last name',
	page_register_gender_error: 'Indicate your gender',
	page_register_country_error: 'Indicate your country',
	page_register_email_error: 'Indicate a valid email address',
	page_register_username_error: 'Choose a username',
	page_register_password_error: 'The password is not valid',
	page_register_confirmation_error: 'Error in password confirmation',
	page_register_global_error: 'There were some errors, see instructions in red above',
	page_register_get_email_notice: [
	  'Thank you for your registration. An email has been sent to <a href="mailto:%%EMAIL%%">%%EMAIL%%</a> with a confirmation link. Please follow this link to complete your registration.',
    'If you have not received this email within a few minutes then check the <b>Junk</b> or <b>Spam</b> folder, it\'s inevitably there !',
    'See you soon on the site !'
  ],
	page_register_completed_notice: [
    'Great ! Your registration is now completed. You can <a href="javascript: void(0)" onclick="return user.sign_in(); return false;">sign in</a> with the username and the password you\'ve chosen and access to the game rooms.',
		'Have fun !'
  ],
	page_register_token_error: 'There was an unexpected problem (probably your session was lost). Please try again',
	page_register_unexpected_error: 'Unexpected error. Please try again',
	page_register_login_exists_error: 'This username already exists',
	page_register_email_exists_error: 'An account has already been registered with this email address',
	page_register_validate: 'Register',
	page_update_title: 'Your account',
	page_update_intro: 'Retrieve below all the informations relative to your account to make changes. Be sure your personal information such as your name and your email will be kept private.',
	page_update_validate: 'Update',
	page_update_ok_title: 'It\'s Ok !',
  page_update_ok_message: 'The modifications have been registered.',
	page_fb_sign_in_title: 'Facebook Sign in',
	page_fb_sign_in_intro: 'Since it\'s the first time you sign in with your Facebook account, please complete your registration with the few informations below, it\'s necessary to access to the game rooms.',
	page_fb_update_title: 'Your account',
	page_fb_update_intro: 'Retrieve below all the informations relative to your account to make changes.',
  page_game_rooms_title: 'Game rooms',
	page_game_rooms_rooms_intro: 'Below is the list of the available game rooms at the moment. Click on a room to enter.',
	page_game_rooms_room: 'Room',
	page_game_rooms_rules: 'Rules',
	page_game_rooms_user_in_room: 'player in the room',
	page_game_rooms_users_in_room: 'players in the room',
	page_game_rooms_game_in_course: 'current game',
	page_game_rooms_games_in_course: 'current games',
	page_game_rooms_in_room_intro: 'Below is the list of the available players and the current games. Click on a user to invite him for a game.',
	page_game_rooms_in_room_back: 'Back to the rooms list',
	page_game_rooms_in_room_quit: 'Quit Room',
	page_game_rooms_available_players: 'available players',
};